// ═══════════════════════════════════════════════════════════════════════════
// Power BI DAX Measures for Affinity Explorer
// ═══════════════════════════════════════════════════════════════════════════
//
// These measures replicate the key calculations from the Streamlit app.
// Create a new "Measures" table in Power BI and add these one by one.
//
// PREREQUISITES:
//   Import the CSVs from powerbi_data_prep.py first, then create
//   relationships as described in POWERBI_SETUP.md.
//
// TABLE REFERENCES:
//   fact_segment_stats  – pre-computed stats (primary analytics table)
//   fact_observations   – row-level data (for custom slicing)
//   dim_segments        – segment dimension
//   dim_communications  – communication dimension
// ═══════════════════════════════════════════════════════════════════════════


// ─── BASIC METRICS (from fact_segment_stats) ────────────────────────────────

// Treated mean balance % change (weighted by current filter context)
Treated Mean Bal% =
AVERAGE(fact_segment_stats[treated_mean_bal])

// Treated mean accounts % change
Treated Mean Acct% =
AVERAGE(fact_segment_stats[treated_mean_acct])

// Control mean balance % change
Control Mean Bal% =
AVERAGE(fact_segment_stats[control_mean_bal])

// Control mean accounts % change
Control Mean Acct% =
AVERAGE(fact_segment_stats[control_mean_acct])


// ─── LIFT METRICS ───────────────────────────────────────────────────────────

// Balance lift (treatment - control), N-weighted across filtered segments
Lift Bal% (N-weighted) =
VAR _total_n = SUM(fact_segment_stats[n_treated])
RETURN
    IF(
        _total_n > 0,
        SUMX(
            fact_segment_stats,
            fact_segment_stats[lift_bal] * fact_segment_stats[n_treated]
        ) / _total_n,
        BLANK()
    )

// Accounts lift, N-weighted
Lift Acct% (N-weighted) =
VAR _total_n = SUM(fact_segment_stats[n_treated])
RETURN
    IF(
        _total_n > 0,
        SUMX(
            fact_segment_stats,
            fact_segment_stats[lift_acct] * fact_segment_stats[n_treated]
        ) / _total_n,
        BLANK()
    )

// Single-cell lift (for matrix visuals — no aggregation needed)
Lift Bal% = AVERAGE(fact_segment_stats[lift_bal])
Lift Acct% = AVERAGE(fact_segment_stats[lift_acct])
Lift CI Bal = AVERAGE(fact_segment_stats[lift_ci_bal])
Lift CI Acct = AVERAGE(fact_segment_stats[lift_ci_acct])


// ─── SIGNIFICANCE FLAG ──────────────────────────────────────────────────────

// 1 if lift is statistically significant at 95% level
Is Significant (Bal) =
IF(
    NOT(ISBLANK([Lift Bal%])) && NOT(ISBLANK([Lift CI Bal])),
    IF(
        ([Lift Bal%] - [Lift CI Bal]) > 0 || ([Lift Bal%] + [Lift CI Bal]) < 0,
        1,
        0
    ),
    BLANK()
)


// ─── SAMPLE SIZE ────────────────────────────────────────────────────────────

Total Treated Customers = SUM(fact_segment_stats[n_treated])
Total Control Customers = SUM(fact_segment_stats[n_control])
Unique Customers =
DISTINCTCOUNT(fact_observations[alpha_key])


// ─── PROJECTED IMPACT ───────────────────────────────────────────────────────

// Projected absolute € balance increase
Projected Balance Increase (€) =
SUMX(
    fact_segment_stats,
    IF(
        NOT(ISBLANK(fact_segment_stats[projected_bal_increase])),
        fact_segment_stats[projected_bal_increase],
        0
    )
)

// Projected account openings
Projected Account Increase =
SUMX(
    fact_segment_stats,
    IF(
        NOT(ISBLANK(fact_segment_stats[projected_acct_increase])),
        fact_segment_stats[projected_acct_increase],
        0
    )
)


// ─── DATA QUALITY METRICS ───────────────────────────────────────────────────

// % of observations with missing balance data
Missing Balance % =
DIVIDE(
    COUNTBLANK(fact_observations[balance_pct_change]),
    COUNTROWS(fact_observations)
)

// % of observations with missing accounts data
Missing Accounts % =
DIVIDE(
    COUNTBLANK(fact_observations[accounts_pct_change]),
    COUNTROWS(fact_observations)
)

// % of customers in more than one segment
Multi-Segment % =
VAR _multi =
    COUNTROWS(
        FILTER(
            SUMMARIZE(fact_observations, fact_observations[alpha_key], "seg_count",
                DISTINCTCOUNT(fact_observations[nsegment])),
            [seg_count] > 1
        )
    )
VAR _total = DISTINCTCOUNT(fact_observations[alpha_key])
RETURN DIVIDE(_multi, _total)

// Contact rate
Contact Rate % =
DIVIDE(
    CALCULATE(COUNTROWS(fact_observations), fact_observations[contact_flag] = 1),
    COUNTROWS(fact_observations)
)


// ─── COMBO EXPLORER MEASURES (from fact_combo_pairs) ────────────────────────

Combo Count = COUNTROWS(fact_combo_pairs)

Positive Synergy Count =
CALCULATE(
    COUNTROWS(fact_combo_pairs),
    fact_combo_pairs[synergy] > 0
)

Best Synergy =
MAX(fact_combo_pairs[synergy])

Avg Combo Lift Bal% =
AVERAGE(fact_combo_pairs[combo_lift_bal])


// ─── CO-OCCURRENCE ──────────────────────────────────────────────────────────

// For the co-occurrence matrix visual
Overlap % = AVERAGE(fact_cooccurrence[overlap_pct])
Shared Customers = SUM(fact_cooccurrence[shared_customers])


// ─── CONDITIONAL FORMATTING HELPERS ─────────────────────────────────────────

// Returns a color hex for RdYlGn scale based on lift value
// Use this in Power BI conditional formatting → Field value
Lift Color =
VAR _val = [Lift Bal%]
VAR _lo = -0.10
VAR _hi = 0.10
VAR _t = MIN(1, MAX(0, (_val - _lo) / (_hi - _lo)))
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(_val), BLANK(),
        _t < 0.25, "#F8696B",    // Red
        _t < 0.50, "#FFAA44",    // Orange
        _t < 0.75, "#FFEB84",    // Yellow
        "#63BE7B"                 // Green
    )

// N (sample size) color — red < 30 < yellow < 100 < green
N Color =
VAR _n = SUM(fact_segment_stats[n_treated])
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(_n) || _n = 0, BLANK(),
        _n < 30, "#F8696B",
        _n < 100, "#FFEB84",
        "#63BE7B"
    )


// ─── JOURNEY TIMELINE ───────────────────────────────────────────────────────

Journey Bal% = AVERAGE(fact_journey[mean_bal_pct])
Journey Acct% = AVERAGE(fact_journey[mean_acct_pct])
Journey Customers = SUM(fact_journey[n_customers])
